### PR TITLE
Stop component deletion and bug fix for no existing locations.

### PR DESCRIPTION
**Pull request by tokejepsen**
Fix for when components gets created without a location. This can happen when the integration fails for whatever reason.

### CODE REVIEW

**Comment by tokejepsen** [comment]
The latest commit actually changes this PR to be very important. The previous behaviour of deleting the component to overwrite the component data, was not recommended workflow. Other Ftrack integrations like the Asset Manager assumes the component id stays the same, so deleting the component would break the connection.
This PR fixes this, so the component once created will never be deleted. When requesting to overwrite the component data, only the data gets overwritten.

**Comment by tokejepsen** [comment]
@mkolar and @mottosso, do you mind if I merge this?

**Comment by mottosso** [comment]
You have full autonomy here, it's up to you.

**Review by mottosso — APPROVED** [review]
No comment.

**Review by mkolar — APPROVED** [review]
Let's merge this. It makes sense to comply to the ftrack standard closely

**Pull request merged**
