### PR TITLE
A few bugfixes and unified ftrack_component plugin

### PR DESCRIPTION
**Pull request by mkolar**
I had a few bug in the code that I fixed and tested now. 

Also I've merged component uploading into a single plugin which runs on all instances and looks for required data members.
`instance.data('ftrackComponent')`
`instance.data('ftrackComponentName')`

this makes it work on any instance that get's this data attached at anytime during publishing, because ftrack conforming is offset to run after other conformers, to make sure we have final paths for each file.

### CODE REVIEW

**Comment by mottosso** [comment]
What do you think about adding some tests to the repo? I can setup Travis to run on pull-requests.

Also don't forget to provide some instructions on how to get setup and use it.
- https://github.com/pyblish/pyblish/wiki/Writing-Extensions

**Comment by mkolar** [comment]
We can certainly add some tests in there. So be honest though I haven't used them before and I'm not quite sure how to do it :). 

I'll add some instructions into readme today.

**Comment by mottosso** [comment]
Did you mean you haven't used the plug-ins, or that you haven't written tests before?

For tests, use Nose, and have a look at the [Pyblish tests](https://github.com/pyblish/pyblish/blob/master/pyblish/tests/test_plugins.py) for reference.

In a nutshell, each function is a start-to-finish script for a small feature that assumes a certain outcome.  If the outcome isn't as expected, the test has failed. In this case, I was thinking you could make a test for what you just tested, for the bug you just fixed, so that it at least one test fails if it ever happens again.

**Comment by mkolar** [comment]
Yep I meant tests. I had a look at the ones in pyblish and I see what you meant. Might by tricky to iclude them here due to dependency on ftrack_connect. might be more work than it's worth. Anyways if I find some time I'll have a look at it. 

I think we've come to a very usable and simple to setup version now. I didn't have time to add any docs yet, but will get to it soon.

**Comment by mottosso** [comment]
Cool, merging changes.

**Pull request merged**
