### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mkolar**
Instruction about how to use pyblish-ftrack

### CODE REVIEW

**Comment by mkolar** [comment]
@mottosso what do you think about documenting like this?

**Comment by mottosso** [comment]
Having a look

**Comment by mottosso** [comment]
Looks good to me, clear and concise.

Wish I could test it though. Roughly speaking, what parts of the ftrack API is involved in this extension?

E.g.

``` python
ftrack
ftrack.Project
ftrack.Task
```

And what functionality do they provide, roughly?

What I'm thinking is that we should have a look at mocking it for sake of testing, both by hand and automatically. If you could tell me a bit more about how those objects are generally meant to act, I might be able to throw together a mock rather quickly.

**Comment by mottosso** [comment]
Also, consider putting the documentation in the Wiki instead, as it makes for easier maintenance and encourages others to update as well. You could then link to the Wiki from the README.

**Comment by mkolar** [comment]
> Also, consider putting the documentation in the Wiki instead, as it makes for easier maintenance and encourages others to update as well. You could then link to the Wiki from the README.

Ah. I though that smaller extension would be kept in readme so people don't have to dig through wikis. I'll move it though that's not an issue.

**Comment by mottosso** [comment]
No need to dig, the front-page of the Wiki should suffice.

But also, don't underestimate the needed amount of documentation (!). I would consider the current README a _glimpse_ into how it works and how to make the best use of it. But I'm certain there will be many questions coming up from anyone taking it up and using it from scratch, and it's that sort of information the documentation should cover.

A wiki is flexible enough to facilitate for this, with support for pages and a sidebar.

**Comment by mkolar** [comment]
> Wish I could test it though. Roughly speaking, what parts of the ftrack API is involved in this extension?

Ftrack has very simple API, however for it to do anything it must access to your ftrack server, where it queries all the data from. For example when you run ftrack.Project(id) it returns Project that matches given ID. Each entity that is returned like this (Project, Shot, Task) is  a subclass of FTObject class if I'm not mistaken. 

Maybe best having a glance at it's API docs which are public including the source. [ftrack api](http://ftrack.rtd.ftrack.com/en/latest/developing/api_reference/index.html)

**Comment by mottosso** [comment]
Yes, what I mean is, a mock would simulate this response.

For example, if `ftrack.Project(id)` returns an instance of type `Project` that could return it's description:

``` python
import ftrack

project = ftrack.Project("myId")
instance.set_data("description", project.getDescription())
```

Then we could mock a response like this.

``` python
import ftrack_mock as ftrack

project = ftrack.Project("myId")
instance.set_data("description", project.getDescription())
```

All that would be required in this case, is to implement `Project` and hardcode an expected response.

**ftrack_mock.py**

``` python
class Project(object):
  def getDescription(self):
    return "I'm a great project"
```

I could dig through their documentation, but we don't want to mock their entire API, that would be fruitless. Instead, I'd like to only mock the parts and responses that you actually use in this extension. I could look at the plug-ins you've written so far, but without an understanding of _why_ it produces the responses it does, it is difficult for me to make a useful mock.

We don't have to do anything right away, but do have a think about what sort of responses you expect from whatever objects you use and try to make note of it. Odds are there isn't very much to mock, which is all the better.

**Comment by mottosso** [comment]
When you continue working after you've made a pull-request, but work on things unrelated to the original request, one thing you can do is branch off. You can always merge from one of your local branches into the master branch, and it keeps pull-requests focused.

I think you should either merge or delete this request to avoid ambiguity.

**Comment by mkolar** [comment]
Agree. I've forgotten about this one to be honest. Deleting.

**Pull request closed without merging**
