### PR TITLE
Code cleanup and issue fixes

### PR DESCRIPTION
**Pull request by mkolar**
Closing issues #8, #11, #13.

Also including DI to reflect changes in pyblish-win

### CODE REVIEW

**Comment by mottosso** [comment]
I notice you are using `name` in place for `label`.

I've had second thoughts about this and am starting to think `name` comes more natural and looks better. What do you think?

**Comment by mkolar** [comment]
Ha. Good point. I actually wasn't sure which one to use, because both were mentioned and then I forgot to double check. I still think that label makes more sense and 'name' in the code was more of a brainfart. What is implemented in the latest pyblish? label?

**Comment by mottosso** [comment]
Yes, it's `label`

**Comment by mkolar** [comment]
ah my bad then. I'll change it to reflect in this pull request

**Comment by mottosso** [comment]
Cool

**Comment by tokejepsen** [comment]
This looks good to me.

**Pull request merged**
