### PR TITLE
Merging all plugins

### PR DESCRIPTION
**Pull request by tokejepsen**
closing #17 
closing #20

### CODE REVIEW

**Comment by mkolar** [comment]
I'd say that the merging was pushed a bit too far. As we were discussing in #17, components creation and uploading should be happening as the very last conformer, so we can be sure that we have the final destination of the files. Otherwise we'd need a conformer, that changes the path attribute of a ftrack component once we know where the published file landed. In the extractor you can only guarantee knowing temporary file path to where the instance is being extracted to, which might be a local disk for example. 

The rest looks good after a quick glance. I'll have a closer look later.

**Comment by tokejepsen** [comment]
Guess I got a bit confused with all the changes. We can just turn the current extractor into a conformer?

**Comment by mkolar** [comment]
The extractor is good and should ideally run as a first of extractors (so we can provide version and asset to other extension if needed (deadline for example) but it should only handle creating asset and assetversion. Component itself I'd delay to conformer.

**Comment by tokejepsen** [comment]
Have updated with conformer component creation

**Comment by mkolar** [comment]
Can't test it out right now. But it looks good so I'm confident it's what was discussed. Merging.

**Pull request merged**
