### PR TITLE
Ftrack hook

### PR DESCRIPTION
**Pull request by tokejepsen**
This should make the Ftrack hook easier for other people to use. Its dependent on pyblish-standalone.

### CODE REVIEW

**Comment by mottosso** [comment]
What is this for? How do I use it?

**Comment by tokejepsen** [comment]
I just realize now that I'm missing any form of documentation on this :worried: 

Its an iteration on the ftrack action; https://www.youtube.com/watch?v=g24YzobsHcc, which now uses pyblish-standalone.

**Comment by tokejepsen** [comment]
I've updated this PR with documentation for the Pyblish action.

Let me know if there are any issues with this.

**Comment by tokejepsen** [comment]
A good workflow I have found with this hook, is to serialize the instances I sent off to the farm. Once the farm has processed the instances, I can publish them without having to open the source host again (Maya for example).

**Comment by tokejepsen** [comment]
Any problems with this PR?

**Comment by mottosso** [comment]
Yes well I still don't know what it does, why you did it or how to use it. There are 2,500 new lines of code so I couldn't exactly sift through it and hope to grok.

How about at least an example, a little snippet, along with an explanation of the problem it solves? Why does anyone need this, and why couldn't they accomplish the thing it does before?

**Comment by tokejepsen** [comment]
I've updated the documentation about this hook; https://github.com/tokejepsen/pyblish-ftrack/blob/master/README.md#ftrack-hook

> Why does anyone need this

The hook is a way of publishing any file type directly from Ftrack. This type of publishing can be done with ftrack-connect, but ftrack-connect lacks everything about CVEI and is just a way of ingesting files into ftrack.

> why couldn't they accomplish the thing it does before

We used to have this hook working, but it died due to not being used in production very much; https://github.com/pyblish/pyblish-ftrack/issues/40.
My new motivation to use it more in production, is to serialize the instances I sent off to the farm. Once the farm has processed the instances, I can publish them without having to open the source host again (Maya for example). This means a better separation between what is published (shared) and what is still a work-in-progress (private), because the farm doesn't automatically publish the renders which hasn't been reviewed by an artist.

As for examples, here I traverse the selected folder for json files to create instances from; https://github.com/bumpybox/pyblish-bumpybox/blob/f2aad5b2cac63d3d57ad09e9ce21270f485db481/pyblish_bumpybox/plugins/collect_json.py

**Comment by mottosso** [comment]
Perfect, thanks for breaking it down for me. :)

With that, I'm happy with this.

**Review by mottosso — APPROVED** [review]

**Pull request merged**
