### PR TITLE
initial version of pyblish action

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mkolar** [comment]
looks good to me. Looking forward to give it a try

**Comment by mottosso** [comment]
Exciting!

Would it be possible to see this in action somehow? Maybe as a gif or youtube clip?

**Comment by mottosso** [comment]
Hah, "in action". :)

**Comment by tokejepsen** [comment]
something like this; http://youtu.be/g24YzobsHcc

**Comment by mottosso** [comment]
Awesome, thanks for that Toke, it gives me a really good idea of what it's for.

From the looks of it, we can speed up the start-up time significantly, if we hook into the same running instance from any of the hosts. It will to get as fast as that, and also get rid of that console.

Let's have a chat about this tomorrow in the chat if you're available.

**Pull request merged**
