### PR TITLE
pyblish-deadline

### PR DESCRIPTION
**Pull request by tokejepsen**
These commits helped with further integration with the new pyblish-deadline

### CODE REVIEW

**Comment by tokejepsen** [comment]
Any problems with merging this?

**Comment by mottosso** [comment]
Should I have this automatically uploaded to PyPI?

**Comment by tokejepsen** [comment]
We could do, but it's not necessary for me. I'm using the `setup.py` when using conda directly from github.
Install fails if there are no `setup.py`.

**Comment by mottosso** [comment]
Cool, works for me.

**Comment by tokejepsen** [comment]
@mkolar have you got any issues with this?

**Comment by mkolar** [comment]
Sorry I didn't have time to have a look before.

No problem. Looks good to me

**Comment by tokejepsen** [comment]
Can't merge :)

**Comment by mottosso** [comment]
Only Milan could merge here.

I've added you in, give it a try!

**Comment by mkolar** [comment]
Ups. my bad, forgot I had the rights here :D

**Pull request merged**
